library(dplyr)
library(ggplot2)
Dayz <- c("1/2/2007","2/2/2007")
RelRange <- filter((read.table("EDA/household_power_consumption.txt", header = T, sep=";", stringsAsFactors = FALSE)), Date %in% Dayz)
RelRange$ConvDt <- strptime((paste(RelevantRange$Date, RelevantRange$Time, sep=" ")), "%m/%d/%Y %H:%M:%S")
par(mfrow = c(2,2))
with(RelRange, {
  plot(RelRange$ConvDt,RelRange$Global_active_power, type = "l", xlab = "", ylab ="Global Active Power (kilowatts)")
  plot(RelRange$ConvDt,RelRange$Voltage, type = "l", xlab = "datetime",ylab="Voltage")
  plot(RelRange$ConvDt, RelRange$Sub_metering_1, type="l", col="black",xlab="",ylab="Energy sub metering")
    lines(RelRange$ConvDt, RelRange$Sub_metering_2, type="l", col="red")
    lines(RelRange$ConvDt, RelRange$Sub_metering_3, type="l", col="blue")
    legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty=1)  
  plot(RelRange$ConvDt,RelRange$Global_reactive_power, type = "l", xlab = "datetime")
})
