library(dplyr)
Dayz <- ("2/1/2007","2/2/2007")
RelRange <- filter((read.table("EDA/household_power_consumption.txt", header = T, sep=";", na.strings=c("", "NA","?"),)), Date %in% Dayz)
RelRange$ConvDt <- strptime((paste(RelevantRange$Date, RelevantRange$Time, sep=" ")), "%m/%d/%Y %H:%M:%S")
plot(RelRange$ConvDt,RelRange$Global_active_power, type = "l", xlab = "", ylab ="Global Active Power (kilowatts)")
