
library(dplyr)
Dayz <- c("1/2/2007","2/2/2007")
RelRange <- filter((read.table("EDA/household_power_consumption.txt", header = T, sep=";", stringsAsFactors = FALSE)), Date %in% Dayz)
RelRange$ConvDt <- strptime((paste(RelRange$Date, RelRange$Time, sep=" ")), "%d/%m/%Y %H:%M:%S")
png(file="Plot3.png")
plot(RelRange$ConvDt, RelRange$Sub_metering_1, type="l", col="black",xlab="",ylab="Energy sub metering")
lines(RelRange$ConvDt, RelRange$Sub_metering_2, type="l", col="red")
lines(RelRange$ConvDt, RelRange$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty=1)
dev.off()
